In [1]:
import numpy as np

In [2]:
array =  np.array([1,2,3,4,5,6,7])

In [3]:
print(array[0]) # 1
print(array[0:3]) # [1 2 3]

1
[1 2 3]


In [5]:
reversed_array = array[::-1] 
print(reversed_array) # [7 6 5 4 3 2 1]

[7 6 5 4 3 2 1]


In [10]:
array1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(array1)
print("-------------------")
print(array1[1,1]) # 7
print("-------------------")
print(array1[:,1]) # [2 7]
print("-------------------")
print(array1[1,1:4]) # [7 8 9]
print("-------------------")
print(array1[-1,:]) # [ 6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-------------------
7
-------------------
[2 7]
-------------------
[7 8 9]
-------------------
[ 6  7  8  9 10]
