In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11, 12,13,14,15])
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [3]:
a = array.reshape(3,5)
print("shape: ", a.shape)
print("dimension: ", a.ndim)

shape:  (3, 5)
dimension:  2


In [6]:
print("data type: ", a.dtype.name)
print("size: ", a.size)
print("type: ", type(a))

data type:  int64
size:  15
type:  <class 'numpy.ndarray'>


In [8]:
array1 = np.array([[1,2,3,4], [5,6,7,8], [9,8,7,5]])

In [9]:
zeros = np.zeros((3,4))

zeros[0,0] = 5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
np.ones((3,4))

np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
a = np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]
