In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a ** b = ", a ** b)

a + b =  [5 7 9]
a - b =  [-3 -3 -3]
a ** b =  [  1  32 729]


In [7]:
print(np.sin(a))
a<2

[0.84147098 0.90929743 0.14112001]


array([ True, False, False])

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]])

# eLement wise prodcut|
print("a * b = ", a * b)

a * b =  [[ 1  4  9]
 [16 25 36]]


In [10]:
# matrix prodcut
a.dot(b.T)
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
print(np.exp(a))


[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [12]:
a = np.random.random((5,5))
print(a)

[[0.56111704 0.50736305 0.69518761 0.39027036 0.01400974]
 [0.20250269 0.52337821 0.14872875 0.42864065 0.82224142]
 [0.70074198 0.60698241 0.43533964 0.64253985 0.05394689]
 [0.8314249  0.88808119 0.09213561 0.94482508 0.67252622]
 [0.94977254 0.96025951 0.6145115  0.43391904 0.58933723]]


In [14]:
print(a.sum())
print(a.max())
print(a.min())

13.709783118632666
0.9602595145270444
0.014009735470321694


In [16]:
print(a.sum(axis=0))
print(a.sum(axis=1))

[3.24555914 3.48606438 1.98590312 2.84019498 2.1520615 ]
[2.1679478  2.12549172 2.43955077 3.428993   3.54779983]


In [21]:
print(np.sqrt(a))
print(np.square(a))

[[0.74907746 0.71229422 0.83377911 0.62471623 0.11836273]
 [0.45000299 0.72344883 0.38565367 0.65470654 0.90677529]
 [0.83710333 0.77909076 0.65980273 0.80158583 0.2322647 ]
 [0.91182504 0.9423806  0.30353848 0.97202113 0.82007696]
 [0.97456274 0.97992832 0.78390784 0.65872531 0.76768303]]
[[3.14852328e-01 2.57417266e-01 4.83285815e-01 1.52310957e-01
  1.96272688e-04]
 [4.10073384e-02 2.73924749e-01 2.21202423e-02 1.83732807e-01
  6.76080955e-01]
 [4.91039322e-01 3.68427643e-01 1.89520601e-01 4.12857459e-01
  2.91026692e-03]
 [6.91267362e-01 7.88688207e-01 8.48897086e-03 8.92694428e-01
  4.52291517e-01]
 [9.02067883e-01 9.22098335e-01 3.77624388e-01 1.88285731e-01
  3.47318373e-01]]
