In [2]:
import numpy as np

In [3]:
array = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# fLatten
a = array.ravel()
print(a)

[1 2 3 4 5 6 7 8 9]


In [10]:
array2 = a.reshape(3, 3)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arrayT = array2.T
print(arrayT)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
print(arrayT.shape)

(3, 3)


In [14]:
array5 = np.array([[1,2], [3,4], [4,5]])
print(array5)

[[1 2]
 [3 4]
 [4 5]]


In [16]:
array5.reshape(2,3)

array([[1, 2, 3],
       [4, 4, 5]])

In [17]:
array5.resize((2,3))