In [1]:
import numpy as np

In [2]:
array1 = np.array([[1,2], [3,4]])
array2 = np.array([[-1,-2], [-3,-4]])

In [4]:
print("array1:\n", array1)
print("array2:\n", array2)

array1:
 [[1 2]
 [3 4]]
array2:
 [[-1 -2]
 [-3 -4]]


In [7]:
# veritical
#array([[1, 2],
#       ［3,4JJ）
#array([[-1, -2],
#       [-3,-4］］）
 
array3 = np.vstack((array1, array2))
 
# horizontal|
# array([[1, 2],[-1, -2],
#       [3, 4]], [-3, -4]1|

array4 = np.hstack((array1, array2))

In [8]:
print("array3:\n", array3)

print("array4:\n", array4)

array3:
 [[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]]
array4:
 [[ 1  2 -1 -2]
 [ 3  4 -3 -4]]
